#!/usr/bin/python3
#Генерирование User Agent

import requests
from bs4 import BeautifulSoup
from utils.generateAgent import head
from utils.loger import Loger 


def ParseResult(response):
    bs = BeautifulSoup(response, 'lxml')
    resultParse = bs.find(['h1']).get_text()
    print(resultParse)

def InitRequest():
    site = 'https://n5m.ru/usagent.html'
    response = requests.get(site, headers=head())
    dataServer = response.headers
    Loger(site, dataServer)
    response.encoding = 'windows-1251' #Добавлено для тестирования, особого значения не имеет
    response = response.text
    ParseResult(response)

InitRequest()

